name: mtcn
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dbus=1.13.18
  - expat=2.3.0
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.68.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - intel-openmp=2021.2.0
  - joblib=1.0.1
  - jpeg=9b
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libidn2=2.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ncurses=6.2
  - nettle=3.7.2
  - ninja=1.10.2
  - numpy=1.20.1
  - numpy-base=1.20.1
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1k
  - pandas=1.2.4
  - pcre=8.44
  - pillow=8.2.0
  - pip=21.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.8.1=py3.8_cuda10.2_cudnn7.6.5_0
  - pytz=2021.1
  - qt=5.9.7
  - readline=8.1
  - scikit-learn=0.23.2
  - scipy=1.6.2
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.35.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchaudio=0.8.1=py38
  - torchvision=0.9.1=py38_cu102
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - chardet==4.0.0
    - click==7.1.2
    - configparser==5.0.2
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - einops==0.3.0
    - epic-kitchens==1.7.1
    - gitdb==4.0.7
    - gitpython==3.1.14
    - gulpio==540.66
    - idna==2.10
    - jinja2==2.11.3
    - markupsafe==1.1.1
    - opencv-python==4.5.2.52
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.16.0
    - psutil==5.8.0
    - pyyaml==5.4.1
    - requests==2.25.1
    - sentry-sdk==1.1.0
    - sh==1.14.1
    - shortuuid==1.0.1
    - smmap==4.0.0
    - subprocess32==3.5.4
    - tensorboardx==2.2
    - tqdm==4.60.0
    - urllib3==1.26.4
    - wandb==0.10.30
    - word2vec==0.11.1
